name = "Stripchart"
uuid = "5dcc7338-8547-45d4-ad80-920326c137c2"
version = "0.1.0"
authors = ["thanasipantazides <thanasipantazides@gmail.com>"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[compat]
Dates = "1.11.0"
GLMakie = "0.13.8"
Revise = "3.13.1"
Sockets = "1.11.0"
